src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_Name;
    /**
     * @ORM\Column(type="boolean")
     *
     *
     */
    private $isVerified = false;
    protected $captchaCode;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_Name;
    }

    public function setLastName(string $last_Name): self
    {
        $this->last_Name = $last_Name;

        return $this;
    }

    /**
     * @return bool
     */
    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    /**
     * @param bool $isVerified
     */
    public function setIsVerified(bool $isVerified): void
    {
        $this->isVerified = $isVerified;
    }

    /**
     * @return mixed
     */
    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    /**
     * @param mixed $captchaCode
     */
    public function setCaptchaCode($captchaCode): void
    {
        $this->captchaCode = $captchaCode;
    }

    /**
     * @return mixed
     */
    public function getResetToken()
    {
        return $this->reset_token;
    }

    /**
     * @param mixed $reset_token
     */
    public function setResetToken($reset_token): void
    {
        $this->reset_token = $reset_token;
    }

}

src/Controller/BackendController.php
<?php

namespace App\Controller;


use App\Entity\User;
use App\Form\RegistrationFormType;

use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;




class BackendController extends AbstractController
{

    

//*****************************************************************************************user back ***********************************************************************


    /**
     * @return Response
     * @route ("/afficheC" , name ="afficheC")
     */
    public function AffichUser (userRepository $repo   ) {
        $abo=$repo->findAll() ;
        return $this->render('backend/afficheruser.html.twig' , [
            'User' => $abo ,
            'ajoutC' => $abo
        ]) ;
    }

    /**
     * @param Request $request
     * @param UserPasswordHasherInterface $userPasswordEncoder
     * @param ManagerRegistry $doctrine
     * @return Response
     * @Route ("/ajoutC" , name="ajoutC")
     */
    function adduser (Request  $request , UserPasswordHasherInterface $userPasswordEncoder , ManagerRegistry $doctrine) {
        $user =  new User () ;
        $formC =  $this->createForm(RegistrationFormType::class,$user) ;
        $formC->add('Ajouter' , SubmitType::class) ;
        $formC->handleRequest($request) ;
        if($formC->isSubmitted()&& $formC->isValid()){
            $user->setPassword(
                $userPasswordEncoder->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $em =  $doctrine->getManager() ;
            $em->persist($user);
            $em->flush();
            return $this ->redirectToRoute('afficheC') ;
        }
        return $this->render('backend/ajouteruser.html.twig' , [
            'formC' => $formC->createView()
        ]) ;
    }
    /**
     * @return void
     * @route ("/updatC{id}" , name="upc")
     */
    function updatec(UserRepository $repo,$id,Request $request,ManagerRegistry $doctrine){
        $user = $repo->find($id) ;
        $formC=$this->createForm(RegistrationFormType::class,$user) ;
        $formC->add('update' , SubmitType::class) ;
        $formC->handleRequest($request) ;
        if($formC->isSubmitted()&& $formC->isValid()){

            $em =  $doctrine->getManager() ;
            $em->flush();
            return $this ->redirectToRoute('afficheC') ;
        }
        return $this->render('backend/updateuser.html.twig' , [
            'formC' => $formC->createView()
        ]) ;

    }

    /**
     * @return void
     * @route ("/deleteC/{id}" ,name ="deleteC" )
     */
    function Deletec($id,UserRepository $repository,ManagerRegistry $doctrine) {
        $user=$repository->find($id) ;
        $em =  $doctrine->getManager() ;
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute("afficheC") ;

    }
}

templates/backend/afficheruser.html.twig
{% extends 'base.back.html.twig' %}

{% block title %}Home Repair - Dashboard{% endblock %}


{% block content %}
    <div class="card">
        <h5 class="card-header">Users</h5>
        <div class="table-responsive text-nowrap">
            <table class="table">
                <thead>
                <tr>

                    <th>last name</th>
                    <th>email</th>
                    <th>Password</th>
                    <th>action</th>
                </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                <tr {% for a in User %}>
                    <td> {{ a.lastName }}</td>
                    <td> {{ a.email }}</td>
                    <td> {{ a.password }}</td>
                    <td> <a href="{{ path('deleteC',{'id':a.id}) }}"> Delete</a> <a href="{{ path('upc',{'id':a.id}) }}"> update</a> </td>
                </tr {% endfor %}>


                </tbody>
            </table>
        </div>
    </div>



{% endblock %}

templates/backend/ajouteruser.html.twig
{% extends 'base.back.html.twig' %}

{% block title %}Home Repair - Dashboard{% endblock %}


{% block content %}
    {% form_theme formC 'bootstrap_4_layout.html.twig' %}
    <div class="templatemo-content-container">
        <div class="templatemo-content-widget white-bg">

            <h2 class="margin-bottom-10">Ajouter un User</h2>

            {{form_start(formC,{'attr' :{'novalidate':'novalidate'}})}}

            {{ form_end(formC) }}

        </div>
    </div>



{% endblock %}

templates/backend/updateuser.html.twig
{% extends 'base.back.html.twig' %}

{% block title %}Home Repair - Dashboard{% endblock %}


{% block content %}
    {% form_theme formC 'bootstrap_4_layout.html.twig' %}
    <div class="templatemo-content-container">
        <div class="templatemo-content-widget white-bg">

            <h2 class="margin-bottom-10">modifier users</h2>

            {{form_start(formC,{'attr' :{'novalidate':'novalidate'}})}}

            {{ form_end(formC) }}

        </div>
    </div>


{% endblock %}